import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  Font,
  Link
} from '@react-pdf/renderer';

// Register a standard font to make sure it looks good and professional
// For production, we'd load a TTF. For now we use the default Helvetica or Times-Roman.

const styles = StyleSheet.create({
  page: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 50,
    fontFamily: 'Helvetica',
  },
  coverPage: {
    padding: 50,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    fontFamily: 'Helvetica',
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: '#1e293b',
  },
  coverSubtitle: {
    fontSize: 16,
    color: '#64748b',
    marginBottom: 40,
    textAlign: 'center',
  },
  coverMeta: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 'auto',
    textAlign: 'center',
  },
  header: {
    fontSize: 10,
    marginBottom: 20,
    textAlign: 'center',
    color: '#94a3b8',
  },
  footer: {
    position: 'absolute',
    fontSize: 10,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: '#94a3b8',
  },
  h1: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 20,
    color: '#0f172a',
  },
  h2: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 15,
    color: '#334155',
  },
  p: {
    fontSize: 12,
    lineHeight: 1.5,
    marginBottom: 10,
    color: '#475569',
  },
  flashcardCard: {
    border: '1pt solid #cbd5e1',
    borderRadius: 4,
    padding: 10,
    marginBottom: 10,
  },
  flashcardQ: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  flashcardA: {
    fontSize: 12,
    color: '#64748b',
  },
  diagramImage: {
    marginVertical: 15,
    width: '100%',
  },
  tocItem: {
    fontSize: 12,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tocLine: {
    flex: 1,
    borderBottom: '1pt dotted #cbd5e1',
    marginHorizontal: 10,
    position: 'relative',
    top: -4,
  }
});

interface StudyGuidePDFProps {
  notebook: any;
  assets: any[];
  selection: any;
  diagramImages: Record<string, string>; // Maps assetId to base64 image
  userName: string;
}

export function StudyGuidePDF({ notebook, assets, selection, diagramImages, userName }: StudyGuidePDFProps) {
  
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <Document>
      {/* Cover Page */}
      {selection.coverPage && (
        <Page size="A4" style={styles.coverPage}>
          <Text style={{ fontSize: 40, marginBottom: 40, color: '#4f46e5', fontWeight: 'bold' }}>
            Scholarly
          </Text>
          <Text style={styles.coverTitle}>{notebook?.title || 'Study Guide'}</Text>
          <Text style={styles.coverSubtitle}>Comprehensive AI-Generated Notes & Visuals</Text>
          
          <View style={{ marginTop: 60, alignItems: 'center' }}>
            <Text style={{ fontSize: 14, marginBottom: 5 }}>Prepared for: {userName || 'Student'}</Text>
            <Text style={{ fontSize: 12, color: '#64748b' }}>Generated on {currentDate}</Text>
          </View>
          
          <Text style={styles.coverMeta}>Generated by Scholarly AI Educational Platform</Text>
        </Page>
      )}

      {/* Main Content Pages */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.header} fixed>
          {notebook?.title || 'Study Guide'}
        </Text>

        {/* Since react-pdf doesn't easily support automatic TOC page number calculation without two passes, 
            we simply list the contents here as a textual outline for now. */}
        {selection.tableOfContents && (
          <View wrap={false} style={{ marginBottom: 30 }}>
            <Text style={styles.h1}>Table of Contents</Text>
            {assets.map((asset, i) => (
              <View style={styles.tocItem} key={i}>
                <Text>{asset.title}</Text>
                <View style={styles.tocLine}></View>
                <Text>{asset.type.replace('_', ' ')}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Iterate over selected assets */}
        {assets.map((asset, index) => {
          
          // Skip logic based on selection
          if (asset.type === 'MIND_MAP' && !selection.mindMaps) return null;
          if (asset.type === 'TIMELINE' && !selection.timelines) return null;
          if (asset.type === 'FLASHCARDS' && !selection.flashcards) return null;
          if (asset.type === 'QUIZ' && !selection.quizzes) return null;
          if ((asset.type === 'NOTES' || asset.type === 'SUMMARY') && !selection.notes && !selection.summaries) return null;

          return (
            <View key={asset.id} wrap={asset.type !== 'MIND_MAP' && asset.type !== 'TIMELINE'} style={{ marginBottom: 20 }}>
              <Text style={styles.h2} break={asset.type === 'MIND_MAP' || asset.type === 'TIMELINE'}>
                {asset.title}
              </Text>
              
              {/* Text rendering for NOTES/SUMMARY */}
              {(asset.type === 'NOTES' || asset.type === 'SUMMARY') && (
                <Text style={styles.p}>
                  {typeof asset.content === 'string' 
                    ? asset.content 
                    : (asset.content.text || asset.content.markdown || asset.content.script || 'No content')}
                </Text>
              )}

              {/* Flashcards */}
              {asset.type === 'FLASHCARDS' && asset.content.cards && (
                <View>
                  {asset.content.cards.map((card: any, idx: number) => (
                    <View key={idx} style={styles.flashcardCard} wrap={false}>
                      <Text style={styles.flashcardQ}>Q: {card.question}</Text>
                      <Text style={styles.flashcardA}>A: {card.answer}</Text>
                    </View>
                  ))}
                </View>
              )}

              {/* Diagrams (Mind Maps, Timelines) */}
              {(asset.type === 'MIND_MAP' || asset.type === 'TIMELINE') && diagramImages[asset.id] && (
                <View>
                  <Image src={diagramImages[asset.id]} style={styles.diagramImage} />
                </View>
              )}
            </View>
          );
        })}

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
          `Page ${pageNumber} of ${totalPages}  |  Generated by Scholarly AI`
        )} fixed />
      </Page>
    </Document>
  );
}
