import { ModelChoice, ModelTier, QueryCategory } from './types';

export interface ModelRouteInput {
  category: QueryCategory;
  complexity: number;
  /** Optional signals for future use — provider health, budgets, user preference. */
  providerHealthy?: boolean;
  latencyBudgetMs?: number;
  tokenBudget?: number;
}

/**
 * Model Router (Task 5) — selects a logical model tier and maps it to a concrete DI provider
 * token. The WorkflowEngine asks the router instead of hardcoding provider logic. Providers are
 * pluggable via the DI container tokens.
 *
 * Behavior preservation: the mapping tier→token keeps the current production choice — the answer
 * is generated by the ReasoningProvider today, so `reasoning` maps to TOKENS.ReasoningProvider and
 * the default plan uses `reasoning`. The `fast`/`balanced` tiers (mapped to the base AIProvider)
 * are only used once model routing consumption is explicitly enabled in a later increment.
 */
export class ModelRouter {
  route(input: ModelRouteInput): ModelChoice {
    const tier = this.tierFor(input);
    return this.forTier(tier, `category=${input.category}, complexity=${input.complexity}`);
  }

  private tierFor(input: ModelRouteInput): ModelTier {
    // Provider degradation would push toward the safer/base tier (future: real health checks).
    if (input.providerHealthy === false) return 'fast';
    if (input.complexity >= 4) return 'reasoning';
    if (input.complexity <= 2) return 'fast';
    return 'balanced';
  }

  private forTier(tier: ModelTier, reason: string): ModelChoice {
    switch (tier) {
      case 'reasoning':
        return { tier, providerToken: 'ReasoningProvider', label: 'reasoning (Grok/Gemini)', reason };
      case 'balanced':
        return { tier, providerToken: 'ReasoningProvider', label: 'balanced', reason };
      case 'fast':
      default:
        return { tier, providerToken: 'AIProvider', label: 'fast (Gemini flash)', reason };
    }
  }

  /** Behavior-preserving default — the current production answer model. */
  default(): ModelChoice {
    return { tier: 'reasoning', providerToken: 'ReasoningProvider', label: 'reasoning (default)', reason: 'default pipeline' };
  }
}

export const modelRouter = new ModelRouter();
