/**
 * Phase A integrity feature flags.
 *
 * Read directly from process.env (not the zod `env` schema) so they are purely additive and
 * cannot break env validation. Every flag can be toggled without a code change; the code paths
 * stay in place when disabled. Defaults are chosen to be safe for a live production system:
 *   - verification + repair ON (they only add integrity checks / targeted fixes),
 *   - READY_DEGRADED ON (so a repairable gap does not fail an otherwise-usable source),
 *   - vector metadata backfill ON (the backfill script still requires an explicit run),
 *   - vector re-embed repair OFF by default (it re-embeds and costs money — opt in explicitly).
 */
function boolEnv(name: string, def: boolean): boolean {
  const v = process.env[name];
  if (v === undefined || v === '') return def;
  return /^(1|true|yes|on)$/i.test(v.trim());
}

export const featureFlags = {
  /** Run artifact verification before marking a source READY. */
  get verification(): boolean { return boolEnv('ENABLE_VERIFICATION', true); },
  /** Attempt targeted repair of missing artifacts during verification. */
  get repair(): boolean { return boolEnv('ENABLE_REPAIR', true); },
  /** Allow the READY_DEGRADED status. When false, sources are marked READY regardless. */
  get readyDegraded(): boolean { return boolEnv('ENABLE_READY_DEGRADED', true); },
  /** Enable the Pinecone metadata backfill script to write changes. */
  get vectorMetadataBackfill(): boolean { return boolEnv('ENABLE_VECTOR_METADATA_BACKFILL', true); },
  /**
   * Allow repair to re-embed genuinely-missing vectors from the stored PDF. OFF by default
   * because it incurs embedding cost; when off, missing vectors downgrade to READY_DEGRADED.
   */
  get vectorRepair(): boolean { return boolEnv('ENABLE_VECTOR_REPAIR', false); },
  /**
   * Use the structure-aware chunker (v2) for NEW ingestions. Only affects future ingests;
   * existing v1 chunks/vectors are untouched and remain valid. Toggle off to revert to v1.
   */
  get semanticChunking(): boolean { return boolEnv('ENABLE_SEMANTIC_CHUNKING', true); },
  /**
   * Use the 2-layer knowledge graph linker (deterministic embedding-similarity RELATED_TO edges
   * + LLM directional/typed labels). Toggle off to revert to the LLM-only (v1) linker. Existing
   * edges are untouched either way.
   */
  get twoLayerKG(): boolean { return boolEnv('ENABLE_TWO_LAYER_KG', true); },
  /**
   * Generate the richer educational assets (revision notes, learning objectives, key formulae,
   * high-yield facts, common mistakes, exam tips) in addition to summary/flashcards/quiz.
   * Toggle off to save tokens; the core three are always generated regardless.
   */
  get richAssets(): boolean { return boolEnv('ENABLE_RICH_ASSETS', true); },
  /**
   * Caption figures/diagrams from the source PDF via the multimodal model (Part 10). OFF by
   * default: it sends the whole file to a vision model per ingestion, which is the most
   * expensive per-chapter step. Enable per-deployment when diagram coverage is worth the cost.
   */
  get figureCaptions(): boolean { return boolEnv('ENABLE_FIGURE_CAPTIONS', false); },
  /**
   * Phase 2 Intelligence Layer. When ON, every request is analyzed (category, complexity,
   * workflow/retrieval/model routing) BEFORE retrieval/generation and the resulting ExecutionPlan
   * is logged. In this increment the plan is OBSERVE-ONLY — computed + logged but NOT consumed —
   * so behavior is unchanged. Consumption of routing/model/cache is gated by separate flags added
   * in later increments. Analysis is pure/heuristic (no added latency or cost).
   */
  get intelligenceLayer(): boolean { return boolEnv('ENABLE_INTELLIGENCE_LAYER', true); },
  /**
   * Consume the Intelligence Layer's retrieval strategy (definition→vector-only, research→+web,
   * etc.) instead of always running full GraphRAG. Default OFF — behavior is unchanged until
   * explicitly enabled per deployment after validation.
   */
  get intelligenceRetrievalRouting(): boolean { return boolEnv('ENABLE_INTELLIGENCE_RETRIEVAL', false); },
  /**
   * Consume the Intelligence Layer's model routing (simple queries → fast base model). Default
   * OFF — the answer is generated by the reasoning provider exactly as today until enabled.
   */
  get intelligenceModelRouting(): boolean { return boolEnv('ENABLE_INTELLIGENCE_MODEL', false); },
  /**
   * Semantic response cache — reuse a prior answer for a semantically-similar question (only for
   * stable/cacheable categories: definition/concept/comparison/summary). Default OFF — enabling
   * it can return a previously-generated answer instead of re-running GraphRAG. Safe to enable
   * once validated; misses fall through to the normal pipeline.
   */
  get semanticCache(): boolean { return boolEnv('ENABLE_SEMANTIC_CACHE', false); },
  /**
   * Record per-turn continuous-evaluation + intelligence-analytics (retrieval quality, grounding,
   * routing dimensions) to Firestore, off the critical path. Default OFF — enabling adds a couple
   * of background Firestore writes per request; the response is never affected either way.
   */
  get intelligenceEvaluation(): boolean { return boolEnv('ENABLE_INTELLIGENCE_EVALUATION', false); },

  // ── Phase 3: Adaptive Tutor ────────────────────────────────────────────────
  /**
   * Compute Bloom's-taxonomy level + multi-dimensional semantic complexity on the ExecutionPlan.
   * Pure/heuristic (no LLM, ~0ms), observe-only — nothing consumes these fields until the
   * PromptBuilder increment. Default ON because it cannot change any current output.
   */
  get bloomClassification(): boolean { return boolEnv('ENABLE_BLOOM', true); },
  /**
   * Escalate to an LLM intent classifier for the ambiguous tail (heuristic confidence below
   * threshold). Default OFF — enabling adds at most one small, cached classifier call on
   * genuinely ambiguous queries; confident queries never touch the LLM.
   */
  get hybridIntent(): boolean { return boolEnv('ENABLE_HYBRID_INTENT', false); },
  /**
   * Append the adaptive prompt directive (Bloom/mastery/preferences) to the system prompt.
   * Default OFF — this is the first path that intentionally changes generated output.
   */
  get dynamicPrompt(): boolean { return boolEnv('ENABLE_DYNAMIC_PROMPT', false); },
  /** Track + read per-concept mastery. Default OFF (adds background writes + prompt directives). */
  get mastery(): boolean { return boolEnv('ENABLE_MASTERY', false); },
  /**
   * Continuously infer style preferences (diagrams/concise/detailed/examples/…) from implicit
   * behavior via weighted EMA, in the background. Default OFF — enabling adds one guarded
   * preference write per turn; it never changes output on its own (consumption is via dynamicPrompt).
   */
  get preferenceInference(): boolean { return boolEnv('ENABLE_PREFERENCE_INFERENCE', false); },
  /**
   * Consult the RetrievalOptimizer for adaptive retrieval parameters (top-k/graph depth/reranker).
   * Default OFF — the behavior-preserving default reproduces today's GraphRAG parameters.
   */
  get retrievalOptimization(): boolean { return boolEnv('ENABLE_RETRIEVAL_OPT', false); },
  /**
   * Consult the ModelOptimizer for provider selection from health/latency/budget/quality signals.
   * Default OFF — the behavior-preserving default keeps today's reasoning provider.
   */
  get modelOptimization(): boolean { return boolEnv('ENABLE_MODEL_OPT', false); },
  /**
   * Run the read-only GraphEvolutionService scan (duplicate/isolated/dangling/missing-reciprocal
   * detection). Default OFF. This NEVER mutates the graph — it only produces recommendations.
   */
  get graphEvolution(): boolean { return boolEnv('ENABLE_GRAPH_EVOLUTION', false); },
  /**
   * Warm the embedding + reasoning providers on server boot with a tiny throwaway call, so the
   * first real user request doesn't pay the ~12s cold-start (Vertex auth handshake). Non-blocking
   * and guarded; default ON.
   */
  get warmup(): boolean { return boolEnv('ENABLE_WARMUP', true); },

  /**
   * Podcast Style Engine. When ON, the selected style (Teacher & Student,
   * Storytelling, Documentary, Interview, Debate, Solo Narration) drives the
   * cast, the episode structure, question frequency, pacing and the Director's
   * cinematic parameters — see core/workflow/podcast/podcastStyles.ts.
   *
   * Default OFF so behaviour is unchanged until explicitly enabled. With it off,
   * the legacy `speakerStyle` path runs exactly as before, in which three of the
   * six UI labels collapse onto 'solo_narrator' and produce identical episodes.
   */
  get enhancedPodcastStyles(): boolean { return boolEnv('ENHANCED_PODCAST_STYLES', false); },

  // ── AI Director / AI Producer platform (see AI_DIRECTOR_ARCHITECTURE.md) ───
  /**
   * Master switch for the AI Producer + AI Director planning layers. Default OFF.
   * When OFF, nothing in core/director or core/producer executes and podcast
   * generation is byte-for-byte today's behavior.
   */
  get aiDirector(): boolean { return boolEnv('AI_DIRECTOR_ENABLED', false); },
  /**
   * Shadow Mode: run the Producer + Director, persist ProducerPlan and
   * MasterTimeline, but keep rendering audio with the existing AudioComposer.
   * Users receive exactly the same podcast while planning quality is validated
   * at zero production risk. Default ON so that enabling `aiDirector` alone can
   * never change user-visible output.
   */
  get aiDirectorShadowMode(): boolean { return boolEnv('AI_DIRECTOR_SHADOW_MODE', true); },
  /**
   * Run the AI Producer stage. Separate from the Director so the pedagogical
   * layer can be validated independently. Default OFF.
   */
  get aiProducer(): boolean { return boolEnv('AI_PRODUCER_ENABLED', false); },
  /**
   * Route emotional lines to an expressive TTS provider (ElevenLabs). This is
   * the only cost-significant flag in the platform — see the Stage 4 gate in
   * AI_DIRECTOR_ARCHITECTURE.md §18 risk 2. Default OFF.
   */
  get emotionVoices(): boolean { return boolEnv('EMOTION_VOICES_ENABLED', false); },
};

/**
 * Which cinematic tracks the audio renderer is allowed to mix, as a CSV subset
 * of `music,ambience,sfx,pause`. Empty (the default) means voice only, i.e.
 * today's behavior. This is the incremental-rollout dial for migration
 * Stages 1–3: widen it one track at a time.
 */
export function cinematicTracks(): Set<'music' | 'ambience' | 'sfx' | 'pause'> {
  const raw = (process.env.CINEMATIC_TRACKS || '').trim();
  if (!raw) return new Set();
  const allowed = new Set(['music', 'ambience', 'sfx', 'pause'] as const);
  const out = new Set<'music' | 'ambience' | 'sfx' | 'pause'>();
  for (const part of raw.split(',')) {
    const t = part.trim().toLowerCase();
    if ((allowed as Set<string>).has(t)) out.add(t as 'music' | 'ambience' | 'sfx' | 'pause');
  }
  return out;
}

/** Global cinematic intensity. Defaults to `subtle` so audio never competes with comprehension. */
export function cinematicIntensity(): 'subtle' | 'balanced' | 'dramatic' {
  const v = (process.env.CINEMATIC_INTENSITY || 'subtle').trim().toLowerCase();
  return v === 'balanced' || v === 'dramatic' ? v : 'subtle';
}

/** Mastering loudness target in LUFS. Podcast standard is -16. */
export function targetLufs(): number {
  const n = Number.parseFloat(process.env.TARGET_LUFS || '');
  return Number.isFinite(n) && n <= -6 && n >= -30 ? n : -16;
}

/** Current MasterTimeline schema generation (v1 = legacy implicit, v2 = explicit timeline). */
export const TIMELINE_VERSION = 2;

/** Current version of the verification logic (bump when checks change materially). */
export const VERIFICATION_VERSION = 1;
/** Current version of the normalized Pinecone metadata shape. */
export const METADATA_VERSION = 1;
/** Current knowledge-graph generation: 2 = two-layer (similarity + LLM typing). */
export const GRAPH_VERSION = 2;
