import { Router } from 'express';
import questionsRoutes from './questions.routes';
import testsRoutes from './tests.routes';
import plannerRoutes from './planner.routes';
import leaderboardRoutes from './leaderboard.routes';
import discussionsRoutes from './discussions.routes';
import roomsRoutes from './rooms.routes';
import usersRoutes from './users.routes';
import teacherRoutes from './teacher.routes';
import classesRoutes from './classes.routes';
import enrollmentsRoutes, { invitationsRouter } from './enrollments.routes';
import chatRoutes from './chat.routes';
import companionRoutes from './companion.routes';
import notebooksRoutes from './notebooks.routes';
import studyGroupsRoutes from './studyGroups.routes';
import publishedAssetsRoutes from './publishedAssets.routes';
import briefingRoutes from './briefing.routes';
import graphRoutes from './graph.routes';
import assetsRoutes from './assets.routes';
import feedbackRoutes from './feedback.routes';
import enterpriseAdminRoutes from '../admin/routes/admin.routes';
import analyticsRoutes from './analytics.routes';

// Modern Routes
import baselineAssessmentRoutes from './baselineAssessment.routes';
import connectionsRoutes from './connections.routes';
import cronRoutes from './cron.routes';
import dmRoutes from './dm.routes';
import documentsRoutes from './documents.routes';
import doubtsRoutes from './doubts.routes';
import mediaRoutes from './media.routes';
import notificationsRoutes from './notifications.routes';
import paymentsRoutes from './payments.routes';
import planningRoutes from './planning.routes';
import podcastsRoutes from './podcasts.routes';
import quizRoutes from './quiz.routes';
import scanRoutes from './scan.routes';
import trashRoutes from './trash.routes';
import uploadsRoutes from './uploads.routes';
import videoLessonRoutes from './video-lesson.routes';
import webhooksRoutes from './webhooks.routes';
import helpRoutes from './help.routes';
import examRoutes from './exam.routes';

const router = Router();

router.use('/analytics', analyticsRoutes);
router.use('/briefing', briefingRoutes);
router.use('/questions', questionsRoutes);
router.use('/tests', testsRoutes);
router.use('/planner', plannerRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/discussions', discussionsRoutes);
router.use('/rooms', roomsRoutes);
router.use('/users', usersRoutes);
router.use('/teacher', teacherRoutes);
router.use('/classes', classesRoutes);
router.use('/enrollments', enrollmentsRoutes);
router.use('/invitations', invitationsRouter);
router.use('/chat', chatRoutes);
router.use('/chat', feedbackRoutes);
router.use('/companion', companionRoutes);
router.use('/notebooks', notebooksRoutes);
router.use('/notebooks', graphRoutes);
router.use('/notebooks', assetsRoutes);
router.use('/study-groups', studyGroupsRoutes);
router.use('/explore', publishedAssetsRoutes);
router.use('/admin', enterpriseAdminRoutes);

// Mount Modern Routes
router.use('/baseline-assessment', baselineAssessmentRoutes);
router.use('/connections', connectionsRoutes);
router.use('/cron', cronRoutes);
router.use('/dm', dmRoutes);
router.use('/documents', documentsRoutes);
router.use('/doubts', doubtsRoutes);
router.use('/media', mediaRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/payments', paymentsRoutes);
router.use('/planning', planningRoutes);
router.use('/podcasts', podcastsRoutes);
router.use('/quiz', quizRoutes);
router.use('/scan', scanRoutes);
router.use('/trash', trashRoutes);
router.use('/uploads', uploadsRoutes);
router.use('/video-lesson', videoLessonRoutes);
router.use('/webhooks', webhooksRoutes);
router.use('/help', helpRoutes);
router.use('/exams', examRoutes);

export default router;
