jest.mock('../../src/utils/logger', () => ({
  logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn(), log: jest.fn() },
}));
// Control verification without touching RetrievalService/network.
jest.mock('../../src/core/workflow/services/VerificationService', () => ({
  verificationService: { verify: jest.fn().mockResolvedValue(null) },
}));

import { GenerationOrchestrator } from '../../src/core/workflow/services/GenerationOrchestrator';
import { verificationService } from '../../src/core/workflow/services/VerificationService';
import { container, TOKENS } from '../../src/core/di/container';
import { WorkflowEvent } from '../../src/core/workflow/types';

async function drain<R>(gen: AsyncGenerator<WorkflowEvent, R>) {
  const events: WorkflowEvent[] = [];
  let res = await gen.next();
  while (!res.done) { events.push(res.value); res = await gen.next(); }
  return { events, outcome: res.value };
}

// A provider stub whose generateStreamResponse yields the given chunks.
const streamingProvider = (chunks: string[], onCall?: () => void) => ({
  generateStreamResponse: async function* () { onCall?.(); for (const c of chunks) yield c; },
  generateResponse: jest.fn(),
});

const baseParams = (over: any = {}) => ({
  req: { userId: 'u1', query: 'explain gauss law', history: [], traceId: 't1', ...(over.req || {}) },
  mode: 'TEACHER',
  studentContext: { isOnboarded: true } as any,
  agentContext: { request: {} as any, retrievedContext: 'ctx', sharedState: {} as any },
  citationsList: over.citationsList ?? [],
  hasAttachment: false,
  workflowStartTime: Date.now(),
  ...over,
});

describe('GenerationOrchestrator', () => {
  beforeEach(() => {
    container.clear();
    (verificationService.verify as jest.Mock).mockReset().mockResolvedValue(null);
  });
  afterEach(() => container.clear());

  it('streams reasoning + AGENT_EXECUTION progress + answer chunks and returns the reply', async () => {
    container.register(TOKENS.AIProvider, streamingProvider(['thinking…']));      // reasoning trace
    container.register(TOKENS.ReasoningProvider, streamingProvider(['Hello ', 'world'])); // answer

    const orch = new GenerationOrchestrator();
    const { events, outcome } = await drain(orch.stream(baseParams() as any));

    const types = events.map(e => e.type);
    expect(types).toContain('reasoning');
    expect(types).toContain('progress');   // AGENT_EXECUTION
    expect(types.filter(t => t === 'chunk')).toHaveLength(2);
    expect(outcome.fullReply).toBe('Hello world');
    expect(outcome.generationLatencyMs).toBeGreaterThanOrEqual(0);
    // No notebookId + no citations → verification not invoked.
    expect(verificationService.verify).not.toHaveBeenCalled();
  });

  it('runs verification and emits a warning when a notebook + citations + unsupported claims exist', async () => {
    container.register(TOKENS.AIProvider, streamingProvider([]));
    container.register(TOKENS.ReasoningProvider, streamingProvider(['answer']));
    (verificationService.verify as jest.Mock).mockResolvedValue({
      confidence: 0.5, hallucinationRate: 0.5, citationCoverage: 0.5, warnings: ['claim X'],
    });

    const orch = new GenerationOrchestrator();
    const params = baseParams({
      req: { userId: 'u1', query: 'q', history: [], notebookId: 'nb1', traceId: 't1' },
      citationsList: [{ text: 't', source: 's', score: 0.9 }],
    });
    const { events, outcome } = await drain(orch.stream(params as any));

    expect(verificationService.verify).toHaveBeenCalled();
    const warning = events.find(e => e.type === 'warning');
    expect(warning?.warning).toContain('claim X');
    expect(outcome.measuredConfidence).toBe(0.5);
    expect(outcome.measuredHallucinationRate).toBe(0.5);
  });

  it('model routing (flag on): uses the plan\'s provider token; (flag off): uses ReasoningProvider', async () => {
    const aiCalled = jest.fn();
    const reasoningCalled = jest.fn();
    container.register(TOKENS.AIProvider, streamingProvider(['fast'], aiCalled));
    container.register(TOKENS.ReasoningProvider, streamingProvider(['deep'], reasoningCalled));
    const orch = new GenerationOrchestrator();
    const planFast = { model: { providerToken: 'AIProvider' } } as any;

    // NOTE: the reasoning trace always uses AIProvider, so the reliable discriminator for which
    // provider generated the ANSWER is whether ReasoningProvider was invoked.
    const prev = process.env.ENABLE_INTELLIGENCE_MODEL;
    try {
      // Flag ON + plan chooses fast tier → answer routed to base AIProvider (not ReasoningProvider).
      process.env.ENABLE_INTELLIGENCE_MODEL = 'true';
      await drain(orch.stream(baseParams({ plan: planFast }) as any));
      expect(reasoningCalled).not.toHaveBeenCalled();

      // Flag OFF → answer generated by ReasoningProvider regardless of plan (behavior-preserving).
      reasoningCalled.mockClear();
      process.env.ENABLE_INTELLIGENCE_MODEL = '';
      await drain(orch.stream(baseParams({ plan: planFast }) as any));
      expect(reasoningCalled).toHaveBeenCalled();
    } finally {
      process.env.ENABLE_INTELLIGENCE_MODEL = prev;
    }
  });

  it('failure scenario: a throwing answer provider propagates (not silently swallowed)', async () => {
    container.register(TOKENS.AIProvider, streamingProvider([])); // reasoning is non-fatal
    container.register(TOKENS.ReasoningProvider, {
      generateStreamResponse: async function* () { throw new Error('provider exploded'); },
    } as any);

    const orch = new GenerationOrchestrator();
    const gen = orch.stream(baseParams() as any);
    await expect(drain(gen)).rejects.toThrow('provider exploded');
  });
});
