/**
 * Sample doubts the dashboard avatar "thinks" in its thought cloud. Each is a real, answerable
 * question a student of that exam typically asks; clicking one sends it to the AI tutor.
 *
 * Keyed by the same ExamAvatarKey as examAvatars.ts, so the avatar and its doubts always agree.
 * Every exam has its own list (no sharing), and every question is ≤ 48 characters so it fits the
 * cloud in two lines at phone width.
 */
import { normalizeExam, type ExamAvatarKey } from './examAvatars';

export const EXAM_DOUBTS: Record<ExamAvatarKey, string[]> = {
  NEET: [
    'Why does mitochondria have its own DNA?',
    'Easy way to remember the Krebs cycle?',
    'Mitosis vs meiosis: what really differs?',
    'When is SN1 favoured over SN2?',
    'What is Hardy–Weinberg equilibrium for?',
    'Why is the right lung bigger than the left?',
  ],
  JEE_MAIN: [
    'When do I conserve angular momentum?',
    'Why is the integral of 1/x equal to ln|x|?',
    'How do I spot the limiting reagent fast?',
    'What makes a matrix non-invertible?',
    'Why does a capacitor block DC?',
    'Shortcut for finding the pH of a buffer?',
  ],
  JEE_ADVANCED: [
    'How do I handle rolling with slipping?',
    'When should I use Leibniz integral rule?',
    'Why is a Grignard reagent so basic?',
    'How do I find the locus of a complex number?',
    'Is every continuous function differentiable?',
    'How do I solve variable-mass rocket problems?',
  ],
  UPSC_CSE: [
    'How do Fundamental Rights differ from DPSPs?',
    'Money bill vs finance bill: the difference?',
    'Why was the basic structure doctrine made?',
    'How does El Niño affect our monsoon?',
    'How do I write a 150-word GS answer?',
    'What does the CAG actually audit?',
  ],
  SSC_CGL: [
    'Fastest way to solve pipes and cisterns?',
    'Shortcut for successive percentage change?',
    'How do I solve syllogisms without diagrams?',
    'When do I use "fewer" instead of "less"?',
    'What does Article 21 protect?',
    'How do I solve trigonometry heights fast?',
  ],
  SSC_CHSL: [
    'How do I improve typing speed for the DEST?',
    'Shortcut for simple interest questions?',
    'How do I spot errors in a sentence fast?',
    'How do I solve mirror-image questions?',
    'What is the difference between LAN and WAN?',
    'Quick way to solve average problems?',
  ],
  BPSC: [
    'Why was the Champaran Satyagraha important?',
    'Which major rivers flow through Bihar?',
    'What was the Permanent Settlement of 1793?',
    'Why was Nalanda University famous?',
    'How do I write a strong BPSC mains answer?',
    'What is special about Madhubani painting?',
  ],
  BIHAR_TRE: [
    'What does the RTE Act 2009 guarantee?',
    'How do I manage a class of 60 students?',
    'How should I teach fractions to children?',
    'What is inclusive education in practice?',
    'What is covered in Bihar TRE general studies?',
    'How do I plan a 40-minute lesson?',
  ],
  CTET: [
    "What is Piaget's concrete operational stage?",
    'Formative vs summative assessment?',
    "What is Vygotsky's zone of proximal development?",
    "How does Kohlberg's moral theory work?",
    'What is child-centred pedagogy?',
    'How do I teach EVS through activities?',
  ],
  STET: [
    'How do I explain a hard topic to class 9?',
    "What is Bloom's taxonomy used for?",
    'What is constructivism in teaching?',
    'How do I set a good question paper?',
    'What is action research for teachers?',
    'How do I handle mixed-ability classrooms?',
  ],
  UGC_NET: [
    'Inductive vs deductive: how do I tell?',
    'What is a Type I vs a Type II error?',
    'How do I choose a research design?',
    'Sample vs population: the difference?',
    'How do I solve teaching-aptitude questions?',
    'What counts as plagiarism in research?',
  ],
  IBPS_PO: [
    'How do I crack seating arrangement puzzles?',
    'Shortcut for compound interest over 2 years?',
    'How do I read a DI table quickly?',
    'How do I approach the IBPS PO interview?',
    'Tips for faster reading comprehension?',
    'What is a quadratic inequality question?',
  ],
  SBI_PO: [
    'How do I write the SBI PO descriptive paper?',
    'What does the repo rate actually control?',
    'NEFT vs RTGS vs IMPS: the difference?',
    'How do I solve input–output puzzles?',
    'What is a non-performing asset (NPA)?',
    'How do I clear the SBI group exercise?',
  ],
  RBI_GRADE_B: [
    'What is the difference between CRR and SLR?',
    'How do OMOs change liquidity?',
    'How does monetary policy transmission work?',
    'What does the fiscal deficit measure?',
    'What is Basel III trying to fix?',
    'What is inflation targeting in India?',
  ],
  RRB_NTPC: [
    'How do I solve two trains crossing?',
    'Shortcut for time and work questions?',
    'How do I crack coding–decoding fast?',
    'Speed vs velocity: what is the difference?',
    'How are Indian Railway zones organised?',
    'Quick way to solve age problems?',
  ],
  CUET: [
    'How do I manage time across CUET sections?',
    'What is price elasticity of demand?',
    'How do I solve para-jumble questions?',
    'What is the difference between GDP and GNP?',
    'How do I choose my domain subjects?',
    'How is the CUET score used for admissions?',
  ],
  GATE: [
    'What is the difference between 3NF and BCNF?',
    'How does the Master theorem work?',
    'Why does Dijkstra fail with negative edges?',
    'Paging vs segmentation: the difference?',
    'How do I find a matrix rank quickly?',
    'How do I minimise a DFA?',
  ],
  CDS: [
    'What caused the Revolt of 1857?',
    'How do I speed up elementary maths?',
    'Weather vs climate: what is the difference?',
    'How do I prepare for the SSB interview?',
    'What is the role of the Chief of Defence Staff?',
    'How do I improve English for CDS?',
  ],
  NDA: [
    'How do I solve NDA maths faster?',
    'What is covered in the NDA GAT paper?',
    'How do I clear the SSB screening test?',
    'What is projectile motion used for?',
    'Which article makes the President C-in-C?',
    'How do I stay fit for the SSB?',
  ],
  CBSE: [
    'How do I balance a chemical equation?',
    'How do I write a full-marks board answer?',
    'Why does the Moon show different phases?',
    'Where is Pythagoras theorem used?',
    'How do I learn NCERT diagrams quickly?',
    'How do I score well in CBSE maths?',
  ],
  ICSE: [
    'How do I write an ICSE English composition?',
    'How do I memorise Shakespeare quotes?',
    'How do I draw a neat ray diagram?',
    'How do I solve ICSE physics numericals?',
    'How do I prepare for ICSE history & civics?',
    'What is the law of conservation of mass?',
  ],
  SCHOOL: [
    'Why is the sky blue?',
    'How do plants make their food?',
    'What are prime numbers used for?',
    'Why do we have seasons?',
    'How do I remember what I study?',
    'What makes something float or sink?',
  ],
  STATE_PSC: [
    'What powers does a state Governor have?',
    'How is a State Finance Commission formed?',
    'What does the State Election Commission do?',
    'How do panchayats get their funds?',
    'What is the 73rd Amendment about?',
    'How do I cover state-specific GK?',
  ],
  CA: [
    'Provision vs reserve: the difference?',
    'How does deferred tax arise?',
    'How is GST input tax credit claimed?',
    'What is the going concern assumption?',
    'How do I prepare for CA Foundation law?',
    'What does Ind AS 115 cover?',
  ],
  CMA: [
    'What is marginal costing used for?',
    'How do I calculate the break-even point?',
    'What is activity-based costing?',
    'Standard costing: how is variance found?',
    'What is transfer pricing?',
    'How do I prepare for CMA Inter costing?',
  ],
  CLAT: [
    'Void vs voidable contracts?',
    "What does 'res judicata' mean?",
    'How do I approach legal reasoning passages?',
    'What is the rule of strict liability?',
    'How do I improve reading speed for CLAT?',
    'What is the doctrine of precedent?',
  ],
  GPAT: [
    'How do drugs cross the blood–brain barrier?',
    'What is first-pass metabolism?',
    'Agonist vs antagonist: the difference?',
    'How is bioavailability calculated?',
    'What is the Henderson–Hasselbalch equation?',
    'What is a prodrug?',
  ],
  DEFAULT: [
    'How do I make a study plan that sticks?',
    'How can I remember more of what I read?',
    "What's the best way to revise?",
    'How do I stop procrastinating?',
    'How many hours should I study daily?',
    'How do I stay focused while studying?',
  ],
};

export function getExamDoubts(raw?: string | null): string[] {
  return EXAM_DOUBTS[normalizeExam(raw) || 'DEFAULT'];
}
